{
 "title": "Link shortener stats",
 "description": "Information about link shorteners",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Creation new short link",
   "type": "timeseries",
   "description": "How much new links were created",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(link_created_total[5m]))",
     "legendFormat": "Count of new links"
    }
   ]
  },
  {
   "title": "Error codes in API",
   "type": "timeseries",
   "description": "Error codes in Result block in API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code) (increase(handled_error_total[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Redirect timing",
   "type": "timeseries",
   "description": "Maximum search time int minute and avg",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(link_search_timing_seconds_sum[5m])) / sum(increase(link_search_timing_seconds_count[5m]))",
     "legendFormat": "AVG"
    },
    {
     "expr": "max(link_search_timing_seconds_max)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Redirects statuses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (result_status) (increase(link_visit_total[5m]))",
     "legendFormat": "{{result_status}}"
    }
   ]
  }
 ]
}