server:
  port: ${SERVER_PORT:80}
  jetty:
    threads:
      min: ${HTTP_MIN_THREADS:8}
      max: ${HTTP_MAX_THREADS:100}
      max-queue-capacity: ${HTTP_MAX_QUEUE:100}

logging:
  config: "classpath:logback-spring.xml"
  level:
    dev.alnat: ${BUSINESS_LOG_LEVEL:INFO}

spring:
  application:
    name: tiny-link-shortener
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: postgresql
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tiny_link_shortener}?reWriteBatchedInserts=true&currentSchema=tiny_link_shortener
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      # small and fixed size DB pool is much preferred (see https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing)
      minimum-idle: ${DB_HIKARI_MIN_IDLE:4}
      maximum-pool-size: ${DB_HIKARI_MAX_POOL_SIZE:4}
      auto-commit: ${DB_HIKARI_AUTO_COMMIT:false}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT:30000}
      pool-name: db-hikari-pool
      validation-timeout: ${DB_VALIDATION_TIMEOUT:10000}
  transaction:
    default-timeout: ${DEFAULT_TRANSACTION_TIMEOUT:10}
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    validate-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:/db
    schemas: tiny_link_shortener
    baseline-on-migrate: true
  jackson:
    serialization:
      WRITE_DATE_KEYS_AS_TIMESTAMPS: true
  task:
    # thread pool for async method (for long-pooling request)
    execution:
      pool:
        allow-core-thread-timeout: ${EXECUTION_POOL_ALLOW_TIMEOUT:true}
        core-size: ${EXECUTION_POOL_CORE_SIZE:10}
        max-size: ${EXECUTION_POOL_MAX_SIZE:100}
        keep-alive: ${EXECUTION_POOL_KEEP_ALIVE:60s}
        queue-capacity: ${EXECUTION_POOL_QUEUE_CAPACITY:100}

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  server:
    # Extract actuator to another jetty server for performance reason
    port: ${MANAGEMENT_SERVER_PORT:88}

springdoc:
  swagger-ui:
    # Sort docs in alpha order
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    supportedSubmitMethods: ${SWAGGER_OPERATIONS:"get", "post", "delete"}
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}
  cache:
    disabled: false

custom:
  short-link-generator-mode: ${SHORT_LINK_GENERATOR:SEQUENCE}
  metrics:
    metric-prefix: ${METRIC_PREFIX:}
  paging:
    default-timeout: ${DEFAULT_TASK_PAGING_TIMEOUT:10s}
  proxy:
    is-behind-poxy: ${IS_BEHIND_PROXY:false}
    client-ip-address-header: ${CLIENT_IP_ADDRESS_HEADER:X-IP-ADDRESS}
  qr:
    height: ${QR_HEIGHT:200}
    width: ${QR_WIDTH:200}
    url: ${QR_ENDPOINT:http://localhost:80/s/%s}